// Generated by CoffeeScript 1.8.0
(function() {
  var BackgroundLayer, Layer, bgLayer, layerA;

  Layer = (function() {
    Layer.properties = {
      width: Layer.width,
      height: Layer.height,
      backgroundColor: Layer.backgroundColor,
      position: Layer.position,
      x: Layer.x,
      y: Layer.y,
      borderRadius: Layer.borderRadius
    };

    function Layer(name, properties) {
      var newDiv;
      this.name = name;
      this.properties = properties;
      newDiv = document.createElement('div');
      document.body.appendChild(newDiv);
      newDiv.id = this.name;
      newDiv.style.width = this.properties.width;
      newDiv.style.height = this.properties.height;
      newDiv.style.backgroundColor = this.properties.backgroundColor;
      newDiv.style.position = this.properties.position;
      newDiv.style.left = this.properties.x;
      newDiv.style.top = this.properties.y;
      newDiv.style.borderRadius = this.properties.borderRadius;
    }

    return Layer;

  })();

  BackgroundLayer = (function() {
    BackgroundLayer.properties = {
      backgroundColor: BackgroundLayer.backgroundColor
    };

    function BackgroundLayer(name, properties) {
      var body;
      this.name = name;
      this.properties = properties;
      body = document.getElementsByTagName('body')[0];
      body.style.backgroundColor = this.properties.backgroundColor;
    }

    return BackgroundLayer;

  })();

  layerA = new Layer('layerA', {
    width: '200px',
    height: '100px',
    backgroundColor: '#123456',
    position: 'absolute',
    x: '100px',
    y: '200px',
    borderRadius: '20px'
  });

  bgLayer = new BackgroundLayer('bgLayer', {
    backgroundColor: "#ddd"
  });

}).call(this);
