// Generated by CoffeeScript 1.8.0
(function() {
  var BackgroundLayer, Detect, Errors, Layer, Utils, bgLayer, idArray, layerA, layerB;

  require(['./js/jquery.min'], function(dependency) {});

  require(['./js/velocity.min'], function(dependency) {});

  $(window).resize(function() {
    return location.reload();
  });

  Errors = {
    sameID: 'Two div have the same id! Change the name in the layer declaration.',
    wrongCenterValue: 'You inserted a wrong value for the center properties. Please check it. The only possibilities are: x, y, both.',
    wrongVisibleValue: 'Please insert in layers declaration the visible property for correctness.'
  };

  Detect = {};

  Utils = {};

  Utils.deviceType = function() {
    if (/(mobi)/i.test(navigator.userAgent)) {
      return "phone";
    }
    if (/(tablet)|(iPad)/i.test(navigator.userAgent)) {
      return "tablet";
    }
    return "desktop";
  };

  Detect.isChrome = function() {
    return /chrom(e|ium)/.test(navigator.userAgent.toLowerCase());
  };

  Detect.isSafari = function() {
    return /safari/.test(navigator.userAgent.toLowerCase());
  };

  Detect.isTouch = function() {
    return window.ontouchstart === null;
  };

  Detect.isDesktop = function() {
    return Utils.deviceType() === "desktop";
  };

  Detect.isPhone = function() {
    return Utils.deviceType() === "phone";
  };

  Detect.isTablet = function() {
    return Utils.deviceType() === "tablet";
  };

  if (Detect.isChrome()) {
    console.log('Using Chorme');
  }

  if (Detect.isSafari()) {
    console.log('Using Safari');
  }

  if (Detect.isTouch()) {
    console.log('Using Touch device');
  }

  if (Detect.isDesktop()) {
    console.log('Using Desktop browser');
  }

  if (Detect.isPhone()) {
    console.log('Using Phone');
  }

  if (Detect.isTablet()) {
    console.log('Using Tablet');
  }

  idArray = [];

  Layer = (function() {
    Layer.properties = {
      width: Layer.width,
      height: Layer.height,
      backgroundColor: Layer.backgroundColor,
      position: Layer.position,
      x: Layer.x,
      y: Layer.y,
      z: Layer.z,
      borderRadius: Layer.borderRadius,
      boxShadow: Layer.boxShadow,
      center: Layer.center,
      image: Layer.image,
      visible: Layer.visible,
      opacity: Layer.opacity,
      scale: Layer.scale
    };

    function Layer(name, properties) {
      var centerX, centerY, heightInt, i, screenHeight, screenWidth, tempId, widthInt, _i, _ref;
      this.name = name;
      this.properties = properties;
      window.newDiv = document.createElement('div');
      document.body.appendChild(newDiv);
      newDiv.id = name;
      tempId = name;
      for (i = _i = 0, _ref = idArray.length; 0 <= _ref ? _i < _ref : _i > _ref; i = 0 <= _ref ? ++_i : --_i) {
        if (tempId === idArray[i]) {
          console.error(Errors.sameID);
          document.getElementById('error').style.visibility = 'visible';
        }
      }
      idArray.push(tempId);
      console.log(idArray);
      newDiv.style.width = this.properties.width.toString() + 'px';
      newDiv.style.height = this.properties.height.toString() + 'px';
      newDiv.style.backgroundColor = this.properties.backgroundColor;
      newDiv.style.position = this.properties.position;
      if (this.properties.center === 'both') {
        screenWidth = $(window).width();
        screenHeight = $(window).height();
        widthInt = parseInt(this.properties.width);
        heightInt = parseInt(this.properties.height);
        centerX = (screenWidth - widthInt) / 2;
        centerY = (screenHeight - heightInt) / 2;
        newDiv.style.left = centerX + 'px';
        newDiv.style.top = centerY + 'px';
      } else if (this.properties.center === 'x') {
        screenWidth = $(window).width();
        widthInt = parseInt(this.properties.width);
        centerX = (screenWidth - widthInt) / 2;
        newDiv.style.left = centerX + 'px';
      } else if (this.properties.center === 'y') {
        screenWidth = $(window).height();
        heightInt = parseInt(this.properties.height);
        centerY = (screenWidth - heightInt) / 2;
        newDiv.style.top = centerY + 'px';
      } else {
        newDiv.style.left = this.properties.x + 'px';
        newDiv.style.top = this.properties.y + 'px';
      }
      newDiv.style.zIndex = this.properties.z + 'px';
      newDiv.style.borderRadius = this.properties.borderRadius + 'px';
      newDiv.style.boxShadow = this.properties.boxShadow;
      newDiv.style.backgroundImage = 'url(' + this.properties.image + ')';
      if (this.properties.visible === true) {
        newDiv.style.visibility = 'visible';
      }
      if (this.properties.visible === false) {
        newDiv.style.visibility = 'hidden';
      }
      if (this.properties.visible !== true && this.properties.visible !== false) {
        console.warn(Errors.wrongVisibleValue);
      }
      newDiv.style.opacity = this.properties.opacity;
      newDiv.style.transform = 'scale(' + this.properties.scale + ')';
    }

    Layer.prototype.animate = function(event, x, time) {
      switch (event) {
        case 'opacity':
          $('#' + this.name).velocity({
            opacity: x
          }, time);
          return console.log('Velocity Event: ' + event);
        case 'top':
          $('#' + this.name).velocity({
            top: x + 'px'
          }, time);
          return console.log('Velocity Event: ' + event);
        case 'bottom':
          $('#' + this.name).velocity({
            bottom: x + 'px'
          }, time);
          return console.log('Velocity Event: ' + event);
        case 'x':
          $('#' + this.name).velocity({
            left: x + 'px'
          }, time);
          return console.log('Velocity Event: ' + event);
        case 'y':
          $('#' + this.name).velocity({
            right: x + 'px'
          }, time);
          return console.log('Velocity Event: ' + event);
        case 'translateX':
          $('#' + this.name).velocity({
            translateX: x
          }, time);
          return console.log('Velocity Event: ' + event);
        case 'translateY':
          $('#' + this.name).velocity({
            translateY: x
          }, time);
          return console.log('Velocity Event: ' + event);
        case 'rotateZ':
          $('#' + this.name).velocity({
            rotateZ: x
          }, time);
          return console.log('Velocity Event: ' + event);
        case 'rotateX':
          $('#' + this.name).velocity({
            rotateX: x
          }, time);
          return console.log('Velocity Event: ' + event);
        case 'rotateY':
          $('#' + this.name).velocity({
            rotateY: x
          }, time);
          return console.log('Velocity Event: ' + event);
        case 'width':
          $('#' + this.name).velocity({
            width: x
          }, time);
          return console.log('Velocity Event: ' + event);
        case 'height':
          $('#' + this.name).velocity({
            height: x
          }, time);
          return console.log('Velocity Event: ' + event);
        case 'backgroundColor':
          $('#' + this.name).velocity({
            backgroundColor: x
          }, time);
          return console.log('Velocity Event: ' + event);
        case 'borderRadius':
          $('#' + this.name).velocity({
            borderRadius: x
          }, time);
          return console.log('Velocity Event: ' + event);
        case 'boxShadow':
          $('#' + this.name).velocity({
            boxShadow: x
          }, time);
          return console.log('Velocity Event: ' + event);
        case 'scale':
          $('#' + this.name).velocity({
            scale: x
          }, time);
          return console.log('Velocity Event: ' + event);
      }
    };

    Layer.prototype.edit = function(property, x) {
      var centerX, centerY, heightInt, screenHeight, screenWidth, widthInt;
      switch (property) {
        case 'width':
          document.getElementById(this.name).style.width = x + 'px';
          return console.log('Modified: ' + property);
        case 'height':
          document.getElementById(this.name).style.height = x + 'px';
          return console.log('Modified: ' + property);
        case 'backgroundColor':
          document.getElementById(this.name).style.backgroundColor = x;
          return console.log('Modified: ' + property);
        case 'position':
          document.getElementById(this.name).style.position = x;
          return console.log('Modified: ' + property);
        case 'x':
          document.getElementById(this.name).style.x = x + 'px';
          return console.log('Modified: ' + property);
        case 'y':
          document.getElementById(this.name).style.y = x + 'px';
          return console.log('Modified: ' + property);
        case 'z':
          document.getElementById(this.name).style.z = x + 'px';
          return console.log('Modified: ' + property);
        case 'borderRadius':
          document.getElementById(this.name).style.borderRadius = x + 'px';
          return console.log('Modified: ' + property);
        case 'boxShadow':
          document.getElementById(this.name).style.boxShadow = x;
          return console.log('Modified: ' + property);
        case 'center':
          if (x === 'both') {
            screenWidth = $(window).width();
            screenHeight = $(window).height();
            widthInt = parseInt(document.getElementById(this.name).style.width);
            heightInt = parseInt(document.getElementById(this.name).style.height);
            centerX = (screenWidth - widthInt) / 2;
            centerY = (screenHeight - heightInt) / 2;
            document.getElementById(this.name).style.left = centerX + 'px';
            document.getElementById(this.name).style.top = centerY + 'px';
          } else if (x === 'x') {
            screenWidth = $(window).width();
            widthInt = parseInt(document.getElementById(this.name).style.width);
            centerX = (screenWidth - widthInt) / 2;
            document.getElementById(this.name).style.left = centerX + 'px';
          } else if (x === 'y') {
            screenWidth = $(window).height();
            heightInt = parseInt(document.getElementById(this.name).style.height);
            centerY = (screenWidth - heightInt) / 2;
            document.getElementById(this.name).style.top = centerY + 'px';
          } else {
            document.getElementById('error').style.visibility = 'visible';
            console.error(Errors.wrongCenterValue);
          }
          return console.log('Modified: ' + property);
        case 'image':
          document.getElementById(this.name).style.width = x + 'px';
          return console.log('Modified: ' + property);
      }
    };

    Layer.prototype["delete"] = function() {
      return document.getElementById(this.name).style.visibility = 'hidden';
    };

    return Layer;

  })();

  BackgroundLayer = (function() {
    BackgroundLayer.properties = {
      backgroundColor: BackgroundLayer.backgroundColor,
      image: BackgroundLayer.image
    };

    function BackgroundLayer(properties) {
      var body;
      this.properties = properties;
      body = document.getElementsByTagName('body')[0];
      body.style.backgroundColor = this.properties.backgroundColor;
      body.style.backgroundImage = 'url(' + this.properties.image + ')';
    }

    return BackgroundLayer;

  })();

  layerA = new Layer('layerA', {
    width: 200,
    height: 100,
    backgroundColor: '#efd55a',
    borderRadius: 5,
    position: 'absolute',
    x: 200,
    blur: true
  });

  layerB = new Layer('layerB', {
    width: 200,
    height: 100,
    backgroundColor: '#12ddce',
    borderRadius: 20,
    position: 'absolute',
    center: 'both'
  });

  bgLayer = new BackgroundLayer({
    backgroundColor: "#fff"
  });

  layerB.animate('scale', 2, 2000);

  layerA.edit('width', 300);

  layerB.edit('backgroundColor', '#654321');

}).call(this);
